"""
Configuration for the SeaVision edge inference runtime.

This module has no dependencies on PyTorch or Ultralytics. It must be importable
in the minimal edge enviroment: Python + numpy + OpenCV + PNNX Runtime.
"""

import dataclasses
import json
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict

logger = logging.getLogger(__name__)

ARTIFACT_MANIFEST_FILENAME = "manifest.json"


@dataclass
class ArtifactFile:
    """File entry recorded in an edge artifact manifest."""

    path: str
    sha256: str = ""


@dataclass
class ArtifactManifest:
    """Manifest describing a wheel-first edge artifact directory."""

    schema_version: int = 1
    artifact_version: str = "0.1.0"
    runtime_version_range: str = ">=0.1.0,<0.2.0"
    model: ArtifactFile = field(default_factory=lambda: ArtifactFile("model.onnx"))
    runtime_config: ArtifactFile = field(
        default_factory=lambda: ArtifactFile("config.json")
    )
    export_metadata: ArtifactFile = field(
        default_factory=lambda: ArtifactFile("export_metadata.json")
    )

    @classmethod
    def from_file(cls, path: str | Path) -> "ArtifactManifest":
        """Load an artifact manifest from disk."""
        manifest_path = Path(path)
        if not manifest_path.exists():
            raise FileNotFoundError(f"Artifact manifest not found: {manifest_path}")

        with open(manifest_path, "r", encoding="utf-8") as file_obj:
            data = json.load(file_obj)

        return cls(
            schema_version=data.get("schema_version", 1),
            artifact_version=data.get("artifact_version", "0.1.0"),
            runtime_version_range=data.get(
                "runtime_version_range", ">=0.1.0,<0.2.0"
            ),
            model=ArtifactFile(**data.get("model", {"path": "model.onnx"})),
            runtime_config=ArtifactFile(
                **data.get("runtime_config", {"path": "config.json"})
            ),
            export_metadata=ArtifactFile(
                **data.get(
                    "export_metadata", {"path": "export_metadata.json"}
                )
            ),
        )

    def to_file(self, path: str | Path) -> None:
        """Write the manifest to disk."""
        with open(path, "w", encoding="utf-8") as file_obj:
            json.dump(dataclasses.asdict(self), file_obj, indent=2)


@dataclass
class EdgeConfig:
    """
    COnfiguration for the edge inference runtime.

    This dataclass is the single source of truth for all runtime parameters. It
    can be loaded from a JSON config file (generated by the bundle builder) or
    constructed programmatically.

    Attributes:
        model_path: Path to the exported model file (e.g. model.onnx).
        source: Video source — either a string-encoded integer for a
            camera device index (e.g. "0" for /dev/video0) or a string
            path to a video file or RTSP URL. Default "0" = default
            camera.
        output_dir: Directory for detection CSVs and validation clips.
            Created if it does not exist.
        imgsz: Input image size. Must match the export imgsz exactly.
            Using a different size will produce incorrect or degraded
            detections. The bundle builder sets this automatically from
            the export metadata.
        conf_threshold: Minimum confidence score for detections. Higher
            values reduce false positives but may miss real detections.
        iou_threshold: IoU threshold for non-maximum suppression.
        num_classes: Number of detection classes in the model. Set
            automatically from export metadata.
        class_names: Mapping of class index to human-readable name.
            Set automatically from export metadata.
        validation_clip_interval_s: Seconds between validation clips.
            Set to 0 to disable validation clip recording. Default is
            3600 (one clip per hour).
        validation_clip_duration_s: Duration of each validation clip in
            seconds. Default 30.
        frame_skip: Process every Nth frame. Set to 1 to process every
            frame (default). Higher values reduce CPU load at the cost
            of potentially missing fast-moving objects. For continuous
            monitoring at 25fps, frame_skip=5 (effective 5fps) is often
            a good trade-off on Pi 4.
        ort_threads: Number of ONNX Runtime intra-op threads. Default 0
            means "use all available CPU cores", which matches the
            behaviour in the m3b_pi_benchmark.
        ort_optimization: ONNX Runtime graph optimization level.
            Default "all" enables all optimisations (equivalent to
            ORT_ENABLE_ALL). Use "basic" if you encounter issues.
        csv_flush_interval: Write buffered detections to disk every N
            frames. Lower values are safer (less data loss on crash) but
            cause more disk I/O. Default 100.
        log_level: Python logging level string. Default "INFO".
    """

    model_path: str = "model.onnx"
    artifact_dir: str = ""
    source: str = "0"
    output_dir: str = "./detections"

    imgsz: int = 640
    conf_threshold: float = 0.25
    iou_threshold: float = 0.45
    num_classes: int = 80
    class_names: Dict[int, str] = field(default_factory=dict)

    validation_clip_interval_s: int = 3600
    validation_clip_duration_s: int = 30
    frame_skip: int = 1

    ort_threads: int = 0
    ort_optimization: str = "all"

    csv_flush_interval: int = 100
    log_level: str = "INFO"
    runtime_version_range: str = ""

    @classmethod
    def from_file(cls, path: str) -> "EdgeConfig":
        """
        Load config from a JSON file.
        
        The bundle builder generates this file automatically. Users can edit it
        to tune runtime parameters without modifying code.

        Args:
            path: Path to the JSON configuration file.

        Returns:
            An EdgeConfig instance populated with the values from the file.

        Raises:
            FileNotFoundError: If the config file does not exist.
            json.JSONDecodeError: If the file is not valid JSON.
        """
        config_path = Path(path)
        if not config_path.exists():
            raise FileNotFoundError(f"Config file not found: {path}")

        with open(config_path, "r") as f:
            data = json.load(f)

        # Convert class_names keys from string (JSON limitation) to int
        if "class_names" in data and isinstance(data["class_names"], dict):
            data["class_names"] = {
                int(k): v for k, v in data["class_names"].items()
            }

        return cls(**{
            k: v for k, v in data.items()
            if k in cls.__dataclass_fields__
        })

    @classmethod
    def from_artifact_dir(cls, path: str | Path) -> "EdgeConfig":
        """Load runtime config from a wheel-first artifact directory."""
        artifact_dir = Path(path)
        manifest = ArtifactManifest.from_file(
            artifact_dir / ARTIFACT_MANIFEST_FILENAME
        )

        config = cls.from_file(artifact_dir / manifest.runtime_config.path)

        config.artifact_dir = str(artifact_dir)
        model_path = artifact_dir / manifest.model.path
        config.model_path = str(model_path)
        config.runtime_version_range = manifest.runtime_version_range
        return config
    
    def to_file(self, path: str) -> None:
        """
        Save configuration to a JSON file.

        Args:
            path: Path to write the configuration file.
        """

        data = dataclasses.asdict(self)

        # Convert class_names keys to strings for JSON compatibility
        if "class_names" in data:
            data["class_names"] = {
                str(k): v for k, v in data["class_names"].items()
            }

        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)

        logger.info("Edge config saved to %s", path)