name: seavision
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.21
  - tqdm>=4.60
  - pyyaml>=6.0
  - boto3>=1.26
  - pytorch>=2.0
  - torchvision==0.25
  - pip
  - pip:
      - opencv-python-headless>=4.5
      - ultralytics>=8.3.237
      - onnxruntime


# Add transformers>=4.47